locals {
  # var.tags are applied globally via the provider's default_tags block
  # (terraform.tf). Do NOT merge them in here too — duplicating a tag key
  # across default_tags and resource tags causes a perpetual plan diff.
  common_tags = {
    ManagedBy = "terraform"
  }
  description = "${var.description_prefix} ${var.group}"

  server_labels = merge({
    var.group_discriminator_name = var.group
  }, var.additional_label_selectors)
}

resource "oktapam_group" "user" {
  name = "${var.group}_user"
}
resource "oktapam_group" "admin" {
  name = "${var.group}_admin"
}
resource "oktapam_resource_group" "rg" {
  name        = "${var.group}_rg"
  description = "${local.description}"
  delegated_resource_admin_groups = [
    oktapam_group.admin.id,
  ]
}
# Terraform configuration for Okta resource group project generated by OktaTFResourceGroup (gsoc)
resource "oktapam_resource_group_project" "login" {
  name              = "${var.group}_rg_login"
  resource_group    = oktapam_resource_group.rg.id
  account_discovery = true
  gateway_selector  = var.gateway_selector
}
resource "oktapam_security_policy" "user" {
  name           = "${var.group}_v1_user"
  description    = "Security policy for Okta group ${var.group}_user"
  active         = true
  resource_group = oktapam_resource_group.rg.id

  principals {
    groups = [oktapam_group.user.id]
  }

  # Terraform configuration for Okta security policy for group gsoc generated by OktaTFSecurityPolicyV1 (gsoc_v1_security_policy)
  rule {
    name = "allow_login_user"
    conditions {
      gateway {
        traffic_forwarding = true
        session_recording  = false
      }
    }
    privileges {
      principal_account_ssh {
        enabled                 = true
        admin_level_permissions = false
      }
    }
    resources {
      servers {
        label_selectors {
          server_labels = locals.server_labels
        }
      }
    }
  }
}
resource "oktapam_security_policy" "admin" {
  name           = "${var.group}_v1_admin"
  description    = "Security policy for Okta group ${var.group}_admin"
  active         = true
  resource_group = oktapam_resource_group.rg.id

  principals {
    groups = [oktapam_group.admin.id]
  }

  rule {
    name = "allow_login_admin"
    conditions {
      gateway {
        traffic_forwarding = true
        session_recording  = false
      }
    }
    privileges {
      principal_account_ssh {
        enabled                 = true
        admin_level_permissions = true
      }
    }
    resources {
      servers {
        label_selectors {
          server_labels = locals.server_labels
        }
      }
    }
  }
}
